version: '3'
services:
  web:
    image: nginx:latest
    restart: always

    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'

    ports:
      - '8081:80'

  php:
    build: ./docker
    restart: always

    volumes:
      - '.:/var/www/html'

  db:
    image: postgres:10.1
    restart: always

    volumes:
      - './docker/postgres/data:/var/lib/postgresql/data'

    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpwd

    ports:
      - '5431:5432'









